### ISSUE TITLE
GDPR - Change protection pages

### ISSUE THREAD

**Issue by vvalvesga** [Ibercivis/odourcollect.eu#14]
change the data protection documents so that it adequately includes these changes.

**Comment by EmpressNaledi** [comment]
@AlexAmoSfC to provide the necessary text

**Comment by AlexAmoSfC** [comment]
According to conversation with Rosa Arias, this task was assigned to @frasanz and @vvalvesga prior to my joining (sorry, didn't know! no one commented at the meeting), hence I cannot directly assume this duty. Anyway, of course I'd be more than happy to help them finish the texts, which would be easy to build on top of the examples provided by mapping for change.
Rosa has sent an email to them asking what do they need to finish the task.
Feedback from them needed in order to acknowledge and ensure the task doesn't get stuck.

**Comment by EmpressNaledi** [comment]
This is a task for Ibercivis as the data controller so whether it's @Rosa @frasanz or @vvalvesga - they need to agree internally and update as a matter of urgency. @frasanz maybe handling the technical development but this may not mean that he also compiling the necessary text. Regardless, this needs to be addressed.

**Comment by vvalvesga** [comment]
Done
