### ISSUE TITLE
error in observations to verify as zone admin

### ISSUE THREAD

**Issue by vvalvesga** [Ibercivis/odourcollect.eu#17]
As Superadmin no problem but as Zone Admin, when you want to select observations to verify this error appears:

![imatge](https://user-images.githubusercontent.com/48445869/112388298-3dff1180-8cf3-11eb-8d8e-93186bae397b.png)

**Comment by Javier-Gasca** [comment]
can you check again and describe with more detail what's or where is the problem?

**Comment by AlexAmoSfC** [comment]
I will try, with the help @miguelherpas

**Comment by AlexAmoSfC** [comment]
We have tried to reproduce the issue, clicking on "verify" when in dashboard (Miguel has set my username as zone admin in advance, as per your indications).  


![Anotación 2021-05-21 182002](https://user-images.githubusercontent.com/83209147/119168505-4361a980-ba61-11eb-8a6b-23046561c327.png)

I attach the screenshot of the result, but we have doubts, since the steps to reproduce the issue are a bit ambiguous to us (not sure if "select observations to verify" means just clicking the verify button, or maybe something more?)

Please ellaborate on that and verify if this result confirms the resolution of the issue.

**Comment by frasanz** [comment]
Related #64

**Comment by vvalvesga** [comment]
Solved it. I can't reproduce this error but I think it's working well in both cases (admin and zone admin). I've changed the code because with admin user this feature haven't been working and now it works well.
Code seems to be fine and that error seems impossible to get out because verified field can't be ambiguous , at this moment it's explicitly collected
