### ISSUE TITLE
How to appoint a user as a zone manager?

### ISSUE THREAD

**Issue by Malonsoroldan** [Ibercivis/odourcollect.eu#37]
I've tried to appoint a user as a zone manager of a case study via the 'user' panel, but I got an error 'Oops! Check all the fields'. I've got no possibility to choose anything else rather than the type of user (so I can't specify which case study).
![image](https://user-images.githubusercontent.com/38461022/115874989-0d6edc80-a445-11eb-84b8-740b2fe9f5b4.png)

The second option I have tried is to 1) add a user to a case study through the 'case study' panel and 2) to choose zone manager from the 'user panel'. Didn't work

How can I appoint a user as a zone manager?

**Comment by EmpressNaledi** [comment]
I've tested this in the pre-production & it's working. However, it wasn't super intuitive. 
The text says "Remember that in order to add a user as zone admin, you must have a zone assigned" but it's not obvious that you need to scroll down and select ADD from the Zone List at the bottom of the screen.

I suggest to reword this text to say:
"Remember, to add a user as Zone Admin, first you need to ensure they have been added to the relevant zone from those available in the Zone List below"

**Comment by vvalvesga** [comment]
Replace text suggest for Louise

**Comment by EmpressNaledi** [comment]
The text in https://admin.odourcollect.eu/admin/user hasn't changed
![image](https://user-images.githubusercontent.com/12254027/118247775-7cb37b80-b49b-11eb-9dc6-2c2806bfd06d.png)

**Comment by vvalvesga** [comment]
Not in production yet
