### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by EmpressNaledi** [Ibercivis/odourcollect.eu#45]
Need to check how the timestamp is created in OC & stored in the dashboard - compared to local user timezones

**Comment by EmpressNaledi** [comment]
Looking at the timestamp in the dashboard gives me CET so the data is out by 1hr for those capturing in GMT. Needs also to be tested with users in other time zones

**Comment by AlexAmoSfC** [comment]
Android Emulator set up in Chatham Islands, New Zealand (UTC+12:45)
at the time of annotation, it was 22:13 local time in Chatham Islands, 11:28 local time in Spain.
Hope it helps.

![Screenshot_1621935404](https://user-images.githubusercontent.com/83209147/119475990-ed854e00-bd4d-11eb-95c6-d6d686140d45.png)

**Comment by vvalvesga** [comment]
In database, time is stored in UTC 
In back office in odour list, published at field is calculated like this:

> $userTimezone = new DateTimeZone('Europe/Berlin');
            $gmtTimezone = new DateTimeZone('UTC');
            $myDateTime = new DateTime($odour->published_at, $gmtTimezone);
            $offset = $userTimezone->getOffset($myDateTime);
            $myInterval=DateInterval::createFromDateString((string)7200 . 'seconds');
            $myDateTime->add($myInterval);
            $result = $myDateTime->format('Y-m-d H:i:s');
            $odour->published_at = $result;

it's converting it to CET

In front office, in odour detail as Alex's image, the code doesn't convert to any time zone.

**Comment by AlexAmoSfC** [comment]
Does anybody know why user timezone is hardcoded and forced to CET/CEST?
This has to be extremely unconvenient for @EmpressNaledi and @Malonsoroldan (not to mention is not portable/scalable)

**Comment by AlexAmoSfC** [comment]
To my understanding, the design decision of hardcoding "Europe/Berlin" in OC forces zone admins in countries outsite central Europe time to always see wrong local observation timestamps.
confirmed with @JohanaSfC.
Either, 

- a) we need to show all timestamps in UTC letting the user calculate local offsets for the observation, or 
- b) calculate appropiate time offset of the observations based on zone's actual timezone, not a hardcoded, arbitrary one (obviously, in this case we would need to declare or infer the TZ of a case study accordingly) 

in any case, I retag this as bug since hardcoding Spain-centric values in the code is not acceptable. Let's discuss it in next meeting.
