### ISSUE TITLE
Subtype of odours are not translated to Spanish

### ISSUE THREAD

**Issue by miguelherpas** [Ibercivis/odourcollect.eu#52]
Today on a meeting with citizens, a person downloaded the app and he explained that in the Spanish version, the subtype appears in English.
I've tried it in the front test, and in my phone and it appeared in English as well.

![image](https://user-images.githubusercontent.com/83075623/119548714-c69f3a00-bd96-11eb-9c1e-3db2ef5dade6.png)

**Comment by miguelherpas** [comment]
I´ve checked in different types of odours and in all of them the problem was still occurring.

Please, can it be solved ASAP? as we are in the middle of different small pilots in Spain it is very important for us. 

Thanks!

**Comment by AlexAmoSfC** [comment]
In my tests, it correctly loads the language resources 2nd and further times, failing only at first time. 
In fact, if I change language on the fly, while in "new odour" view, I can see all the texts changing all around the interface EXCEPT the labels assigned to the subtype selection list.

As if i18n was not interacting with this frame at all.

@miguelherpas For the time being, please proceed as follows as a workaround (confirm that it works for you while the bug is being solved):
click on new odour button. new view will load.
click on cancel (top left text). not confuse it with back button of your smartphone.
click on new odour button a second time. Now the view should be in the correct language.

**Comment by AlexAmoSfC** [comment]
I'd suggest to check out the VUE template and search for potential value mismatchings here:
https://github.com/Ibercivis/odourcollect.eu/blob/ff82c50b4f566261bb110809f8a56227696913ef/public-odourcollect/resources/js/views/Odour/OdourCreate.vue#L102

**Comment by AlexAmoSfC** [comment]
Thank you very much, Javier

**Comment by Javier-Gasca** [comment]
You're welcome
